const genresList = [
  'Alternative Music',
  'Blues',
  'Classical Music',
  'Country Music',
  'Dance Music',
  'Easy Listening',
  'Electronic Music',
  'European Music (Folk / Pop)',
  'Hip Hop / Rap',
  'Indie Pop',
  'Inspirational (incl. Gospel)',
  'Asian Pop (J-Pop, K-pop)',
  'Jazz',
  'Latin Music',
  'New Age',
  'Opera',
  'Pop (Popular music)',
  'R&B / Soul',
  'Reggae',
  'Rock',
  'Singer / Songwriter (inc. Folk)',
  'World Music / Beats',
];

module.exports = genresList;
